// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkBGqjlX86I2fqNGZxiC2ms0n12MHlVzY',
    appId: '1:270552038209:web:add300d7b781a202abbfc0',
    messagingSenderId: '270552038209',
    projectId: 'domex-edu',
    authDomain: 'domex-edu.firebaseapp.com',
    storageBucket: 'domex-edu.firebasestorage.app',
    measurementId: 'G-C97CSEJNDE',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoKrm9famRnFaAV5dSPFCdNN-CgwGCcgg',
    appId: '1:270552038209:android:d9937cf8f6e2f039abbfc0',
    messagingSenderId: '270552038209',
    projectId: 'domex-edu',
    storageBucket: 'domex-edu.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9n6Nxp67zEFZV8JFIVgxz9itfVZno0S0',
    appId: '1:270552038209:ios:c9f48311464fa3caabbfc0',
    messagingSenderId: '270552038209',
    projectId: 'domex-edu',
    storageBucket: 'domex-edu.firebasestorage.app',
    iosBundleId: 'com.example.domexEdu',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9n6Nxp67zEFZV8JFIVgxz9itfVZno0S0',
    appId: '1:270552038209:ios:c9f48311464fa3caabbfc0',
    messagingSenderId: '270552038209',
    projectId: 'domex-edu',
    storageBucket: 'domex-edu.firebasestorage.app',
    iosBundleId: 'com.example.domexEdu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkBGqjlX86I2fqNGZxiC2ms0n12MHlVzY',
    appId: '1:270552038209:web:a510d73e7f223906abbfc0',
    messagingSenderId: '270552038209',
    projectId: 'domex-edu',
    authDomain: 'domex-edu.firebaseapp.com',
    storageBucket: 'domex-edu.firebasestorage.app',
    measurementId: 'G-0ZWVV7Y6WH',
  );
}
